import { ThemeProvider } from '@mui/material'
import React from 'react'
import '../globals.css'
import { Inter } from 'next/font/google'
import Applayout from '@/components/Applayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="h-full bg-gray-100">


      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />

      </head>
      <body className="h-full">
        <Applayout>{children}</Applayout>
      </body>
    </html>
  )
}
